### ISSUE TITLE
Update the list of beamlines on the webpage to include x-ray reflectometers

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#1]
The list of neutron beamlines on the website is probably complete but needs appropriate links to be added. 
The list of X-ray beamlines is much more limited and needs to be completed

**Comment by tomarnoldess** [comment]
I have modified the orso beamlines page to create a new table for x-ray reflectometers rather than have them within the neutron table... This is because I think that we should include different more appropriate columns for this table.
I would like to discuss what the right columns are for this table and what beamlines "qualify" as reflectometers. Currently the list includes only liquids reflectometers, but this is clearly too narrow a definition.

**Comment by tomarnoldess** [comment]
A suggestion for column headings:
Facility | Country | Instrument | Liquid surfaces | Polarisation | Energy Range | Other techniques

i.e. remove the reference to TOF for obvious reasons, and instead of horizontal or vertical we highlight whether it works on liquid surfaces which is the real question. two extra columns on the energy range and what other techniques are possible with the beamline.

**Comment by supex179** [comment]
Dear Tom, 
 I think this  is a good list.

**Comment by tomarnoldess** [comment]
Oleg commented that among European synchrotrons a list of beamlines which apply X-ray reflectivity can be generated by selecting Reflectometry box at:
https://www.wayforlight.eu/en/catalogue?Techniques=1394

I took a look at this and actually their definition of reflectometry is not quite the same as ours.
However it is a useful database so i have contacted them and it is possible to set up an API to export data to a portal we could create on our website. 

For now I will add the link above and a disclaimer

**Comment by tomarnoldess** [comment]
Summary of discussion at meeting on 16th September: I have contacted Way for Light and it is clear that we should work with them to give a definition of reflectometry. Some minor edits were suggested for the existing ORSO table, including:
- information about how non-orso memebers can add instruments to the list.
- clarify that we are referring to synchrotron beamlines not all lab based reflectometers
- a better definition of polarisation for x-ray beamlines
