### ISSUE TITLE
conda env create: ResolvePackageNotFound issue (Windows 10)

### ISSUE THREAD

**Issue by acaruana2009** [reflectivity/edu_outreach#25]
I have been trying to build the paper as per the readme in the refl_maths folder. However, I get the following issue:

conda env create --prefix ./refl_maths_env --file environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - scipy=1.5.2

I have scipy 1.5.2 installed. I am new to conda environments so I am assuming I have made a mistake somewhere. Any help would be useful.

Thanks

Andrew

**Comment by arm61** [comment]
Hey Andrew, 

It is a lot more likely that that is my fault (I only did the `environment.yml` stuff this morning so very likely I fucked it up). I have pushed what I think is a fix now. Let me know how it goes.

**Comment by arm61** [comment]
Sorry that is it pushed now, so pull the changes then try

**Comment by acaruana2009** [comment]
OK I have just tried the new version, it solved the first issue but now I have the following (apologies for the long post):

Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package networkx conflicts for:
snakemake=5.15.0 -> networkx[version='>=2.0']
Package python conflicts for:
numpy=1.18.5 -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
pip=19.1.1 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package imagemagick conflicts for:
snakemake=5.15.0 -> imagemagick[version='>=7.0']
Package mkl_random conflicts for:
numpy=1.18.5 -> mkl_random
Package pandas conflicts for:
snakemake=5.15.0 -> pandas
Package snakemake-minimal conflicts for:
snakemake=5.15.0 -> snakemake-minimal=5.15.0
Package vc conflicts for:
python=3.6.8 -> vc[version='>=14.1,<15.0a0']
numpy=1.18.5 -> vc[version='>=14.1,<15.0a0']
Package pygraphviz conflicts for:
snakemake=5.15.0 -> pygraphviz[version='>=1.5']
Package icc_rt conflicts for:
numpy=1.18.5 -> icc_rt[version='>=2019.0.0']
Package mkl_fft conflicts for:
numpy=1.18.5 -> mkl_fft
Package aioeasywebdav conflicts for:
snakemake=5.15.0 -> aioeasywebdav
Package vs2015_runtime conflicts for:
numpy=1.18.5 -> vs2015_runtime[version='>=14.16.27012|>=14.16.27012,<15.0a0']
Package python-irodsclient conflicts for:
snakemake=5.15.0 -> python-irodsclient
Package crc32c conflicts for:
snakemake=5.15.0 -> crc32c
Package mkl conflicts for:
numpy=1.18.5 -> mkl[version='>=2019.4,<2021.0a0']
Package python_abi conflicts for:
pip=19.1.1 -> python_abi=[build='*_cp36m|*_cp27m|*_cp37m']
numpy=1.18.5 -> python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp38|*_cp36m|*_cp37m']
Package pyqt conflicts for:
matplotlib=3.2.0 -> pyqt
Package pygments conflicts for:
snakemake=5.15.0 -> pygments
Package matplotlib-base conflicts for:
matplotlib=3.2.0 -> matplotlib-base[version='>=3.2.0,<3.2.1.0a0']
Package libblas conflicts for:
numpy=1.18.5 -> libblas[version='>=3.8.0,<4.0a0']
Package setuptools conflicts for:
pip=19.1.1 -> setuptools
Package filechunkio conflicts for:
snakemake=5.15.0 -> filechunkio[version='>=1.6']
Package ftputil conflicts for:
snakemake=5.15.0 -> ftputil[version='>=3.2']
Package google-cloud-storage conflicts for:
snakemake=5.15.0 -> google-cloud-storage
Package dropbox conflicts for:
snakemake=5.15.0 -> dropbox[version='>=7.2.1']
Package mkl-service conflicts for:
numpy=1.18.5 -> mkl-service[version='>=2,<3.0a0']
Package wheel conflicts for:
pip=19.1.1 -> wheel
Package blas conflicts for:
numpy=1.18.5 -> blas==1.0=mkl
Package pysftp conflicts for:
snakemake=5.15.0 -> pysftp[version='>=0.2.8']
Package boto3 conflicts for:
snakemake=5.15.0 -> boto3
Package numpy-base conflicts for:
numpy=1.18.5 -> numpy-base=1.18.5
Package jinja2 conflicts for:
snakemake=5.15.0 -> jinja2
Package pip conflicts for:
python=3.6.8 -> pip
Package sqlite conflicts for:
python=3.6.8 -> sqlite[version='>=3.26.0,<4.0a0']
Package jsonschema conflicts for:
snakemake=5.15.0 -> jsonschema
Package libcblas conflicts for:
numpy=1.18.5 -> libcblas[version='>=3.8.0,<4.0a0']
Package liblapack conflicts for:
numpy=1.18.5 -> liblapack[version='>=3.8.0,<3.9.0a0']
Package psutil conflicts for:
snakemake=5.15.0 -> psutil

**Comment by arm61** [comment]
Hmm, it looks like I broke something bad... I will try and sort and double check it works for me before getting you to try again. Sorry about this.

**Comment by arm61** [comment]
So the environment as it stands works for me (so I am guessing this is a Windows bug, as I am on a Mac). 

I reckon there are two options:
- I am about to add a workflow that automagically produces the final paper pdf when there is a commit to the repo (in a special branch), so you could wait till I do that and just submit the .tex files (unaware if you have created broken .tex or not). 
- Alternatively, you could try making some changes in the `Snakefile` to the different versions that are required (I suspect `snakemake` is the problematic version number) and see if you can resolve it.

**Comment by bmaranville** [comment]
I can say that on linux, this had me up and running the paper build in < 10 minutes, and most of the time was spent downloading texlive.  YMMV.
mkvirtualenv refl_maths
pip install snakemake numpy matplotlib scipy refnx emcee seaborn scipy
sudo apt install texlive-science texlive-publishers

snakemake --cores 1

**Comment by acaruana2009** [comment]
maybe I will just use my linux box for this then! Either way, thanks for sorting this out.
