### ISSUE TITLE
Write a news item to send to neutron news and synchrotron news

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#3]
To publicise what ORSO is doing we should write a summary of the recent meeting to distribute as widely as possible

**Comment by tomarnoldess** [comment]
Action from the workshop: Article/Report should include meeting summary, online experience, agreements, steps forward, milestones.

**Comment by aglavic** [comment]
Do you have an example of such an article/report? I could make a start in trying to summarize the various meeting minutes and upload it for others to comment/edit.

**Comment by tomarnoldess** [comment]
Thanks Artur, the current plan is that the chairs write a short summary for their working groups. We then need to collate those and write a wrapper to introduce orso and what we're trying to do. I'm not aware of a precedent but we should review past issues of neutron news to get a flavour of what is appropriate. If you could start doing that it would be very helpful.

**Comment by aglavic** [comment]
Ok, then I'll have a look into this and then contact the chairs.

**Comment by tomarnoldess** [comment]
Submitted an article to SR News. waiting on the outcome before checking copyright issues for putting the same thing into neutron news.

**Comment by tomarnoldess** [comment]
SR news article is accepted in editorial review. I tried also submitting to NR news... Adrian Rennie suggested i contact the editor directly, which he had some details for. I will do that to follow up

**Comment by tomarnoldess** [comment]
Followed up  - all seems to be OK. I will update the article prior to publication in the next issue in Jan
