### ISSUE TITLE
Issue installing conda enviroment 

### ISSUE THREAD

**Issue by wpotrzebowski** [reflectivity/edu_outreach#33]
I have some issues installing conda environment to build paper on OSX 10.15

An error occurred while installing package 'conda-forge::gdk-pixbuf-2.36.12-hb83312c_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::gdk-pixbuf-2.36.12-hb83312c_0
location of failed script: /Users/wojciechpotrzebowski/BA_SPACE/edu_outreach/refl_maths/refl_maths_env/bin/.gdk-pixbuf-post-link.sh

I've updated conda before creating environment

**Comment by arm61** [comment]
Strange, I am running macOS 10.15.5 and it works fine. 

In #25 @bmaranville managed to get things working on linux by just pip installing the relevant packages. That might be easier?

**Comment by acaruana2009** [comment]
I can confirm that Linux worked for me to. My windows didn't work, but I suspect that was to do with how messy my windows anaconda install is...

**Comment by wpotrzebowski** [comment]
Thanks for suggestions! I've managed to make it working with some modifications in yml file:

```
name: refl_maths
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - scipy
  - snakemake
  - pip=19.1.1
  - python=3.6.8
  - pip:
    - refnx
    - emcee
    - seaborn
```

I've been also trying to install pdflatex from texlive-core conda package but it fails to compile paper.tex. I ended up installing MacTex and it works now.

**Comment by arm61** [comment]
Fancy sticking the changes to the yml in a PR?

I think I will update the README.md to include a link to getting a LaTeX compiler, cause I have had a similar issue with the texlive-core conda package before.
