### ISSUE TITLE
Github training for ORSO

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#38]
ORSO members need to know how to use Github

**Comment by andyfaff** [comment]
and git

**Comment by arm61** [comment]
@wpotrzebowski do we want to try and prepare a zoom tutorial or similar? I am sure there is material we can find online (e.g. software carpentry)

**Comment by tomarnoldess** [comment]
@arm61 sorry not got around to adding the detail following our meeting yesterday. The point is that a lot of the peripheral orso members can be a bit scared or overwhelmed with notifications. So we need some very specific instructions about how we want people to engage with orso. i would think some short videos at varying levels would be good, but it might be useful to talk to people to identify what the problems are and maybe have a Q&A section that we can respond to.

**Comment by wpotrzebowski** [comment]
Yes, I think we need to tackle few different levels of complexity:
1. Using github as a forum (creating account, github issues, notifications)
2. Making contributions (commits, pull request)
3. Managing local repositories (pulling, stashing, etc). 

I think videos and Q&A section will do!

**Comment by tomarnoldess** [comment]
I was thinking about this a bit and it would be good if we can phrase this as 'how to interact with orso' rather than how to use github. You can then also include other ways to get involved and it won't sound too scary. The into video would then introduce github etc and lay the foundation for the more complex stuff no. 2 & 3 that @wpotrzebowski suggests.

**Comment by arm61** [comment]
Yeah I think that is a good way to tackle it.

**Comment by arm61** [comment]
@wpotrzebowski do you wanna meet up next week can we can work together on getting some short videos made?

**Comment by wpotrzebowski** [comment]
@arm61: good idea! Let's get it going. I will send invite by email.

**Comment by tomarnoldess** [comment]
I have added a link for lab.github.com which should provide in depth training for anyone interested.
