### ISSUE TITLE
Mailing posts history

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#39]
Mailchimp archive of messages sent.

**Comment by tomarnoldess** [comment]
Not everyone wants to be on all the mailing lists, but that doesn't mean that they are not interested in the activities of the working groups. We should therefore have a way that people can see the information distributed via email. This could be an archive of emails. I also think it would be great if we can automatically put the emails intot he news feed on the website... but i'm not sure if that is feasible. @arm61 any ideas about how to do this?

**Comment by arm61** [comment]
Pragmatic solution is that when we send a mailchimp email, we just copy and paste the content as a news element on the appropriate working group part of the webpage. Don't think we can automate this but I will think about it a bit.

**Comment by arm61** [comment]
https://mailchimp.com/help/about-email-campaign-archives-and-pages/

**Comment by arm61** [comment]
There is now an archive on the homepage.
