### ISSUE TITLE
Establish a mailing list

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#4]
We need a GDPR compliant mailing list

**Comment by tomarnoldess** [comment]
Robert Dalgleish is creating a list using https://www.jiscmail.ac.uk/

**Comment by tomarnoldess** [comment]
From Rob via email:
I’ve just noticed/ remembered a condition on the jiscmail lists. That is that the people need to be 25% UK based (see below).
I’m not sure we’re going to hit that in this case so maybe we need to look at mailchimp after all.

JiscMail provides high quality educational email discussion lists to the UK education and research communities.

All new list requests are checked against the following criteria:

·       PURPOSE: The list should support learning, teaching, research or professional support activities across UK education and research
·       PEOPLE: At least 25% of the subscribers should be from UK Higher Education, Further Education Institutions, Research Communities, Educational Support Organisations or JISC funded projects and services
·       PRIMARY LISTOWNER: The primary list owner should be employed by one of the organisations listed above
·       PARTICIPATION: The subscribers of a list can be from single organisation, or across a range of organisations
Additional information: JiscMail reserves the right to approve or reject a list application. Lists are created based on capacity within the mailing list system. JISCMail reserves the right to close any list which does not meet the current criteria. These criteria are routinely reviewed to ensure they reflect our funding, and the needs of the wider educational community (Last reviewed on 31st August 2016)

**Comment by arm61** [comment]
I have set up a mailing list through mail chimp, it is free to run and a sign up link has been add to the webpage. Shall we close this issue?

**Comment by tomarnoldess** [comment]
Is there any option to sign up to specific working groups? ideally we want a mailing list to communicate general things but do we also need something to manage the "membership" of each working group?

**Comment by arm61** [comment]
Perhaps each chair should create a WG specific mailing list? Rather than having them all "owned" by me

**Comment by tomarnoldess** [comment]
That's fine by me... can you give us some instructions on how to do it - unless it is trivial?

**Comment by arm61** [comment]
I would say it is trivial 

https://mailchimp.com

**Comment by tomarnoldess** [comment]
OK, i'll have a go and if i can do it anyone can ;)

**Comment by tomarnoldess** [comment]
I've managed to create an account and start creating a list. There are a lot of settings so I think there is the potential to have very divergent details. Also if we do it this way then people will have to sign up multiple times... up to 5 different mailing lists. I think that is quite a barrier. I notice there is the option of creating groups within a single list. This seems like a better way of managing the different list because then one would only sign up once and can at that point select which groups to join. So then the question would be can the chairs send out an email if they don't own the list?

**Comment by arm61** [comment]
There must be a way that I can add you as an owner of the list I have set up. Limme investigate

**Comment by arm61** [comment]
I have had a look. On the free account you can have one owner...potentially we set up a gmail account for the chairs and make that the owner?

**Comment by tomarnoldess** [comment]
They want a name and physical address for the owner too, so we'd need to have that too, but otherwise that could work. can you transfer what you've done already to the new owner?

**Comment by arm61** [comment]
...apparently not. I am gonna delete this list and start a new one with a gmail address today

**Comment by tomarnoldess** [comment]
OK, I've deleted mine too. Let me know when the new one is up and running. Are we going to initially add the existing email addresses or ask people to actively sign up?

**Comment by andyfaff** [comment]
I'm pretty sure you're going to have to ask everyone to sign up by themselves. In general I'd assume that a subset of those auto signed up would be upset.

**Comment by tomarnoldess** [comment]
The new mailing list is up and functional. I will send a personal email to everyone indicating that they will need to sign up to receive further information from now on.
