### ISSUE TITLE
SLD database is currently unavailable

### ISSUE THREAD

**Issue by paulmillar** [reflectivity/edu_outreach#42]
Issue #2 closed with the creation of a service at  https://slddb.esss.dk/slddb/

This service is currently unavailable.  Attempts to access this URL returns a "503 Service Unavailable" error response.

**Comment by aglavic** [comment]
This is on ESS, they must have shut it down.

You can temporarily use my private version: http://109.239.60.197:8080/ 

@wpotrzebowski do you know if and when they will let it run again? Or can we make a temporary forward to my site to make it available?

**Comment by wpotrzebowski** [comment]
I've managed to bring it back on-line.

**Comment by paulmillar** [comment]
Looks good to me, thanks!
