### ISSUE TITLE
Restructure the website front page and create blank pages for content

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#5]
Modify the web page to aid navigation and better explain the activities of ORSO

**Comment by tomarnoldess** [comment]
The front page needs to briefly explain what ORSO is, but primarily needs to direct readers to the right part of their website for their interest.
Roughly what we should include (based on message board & subsequent discussions) is:
* Explanation of what ORSO is
* Definitions of what our standards & recommendations are
* News on meetings & calander of events
* Collate existing reference material & education resources
* Links to software and tutorials on use
* Links to relevant beamlines
* FAQs

**Comment by tomarnoldess** [comment]
I have made a start rewriting the home page. It still needs some work on the layout

**Comment by tomarnoldess** [comment]
Significant changes implemented. 

- [x] Explanation of what ORSO is 

- [ ] Definitions of what our standards & recommendations are

- [x] News on meetings & calander of events

- [x] Collate existing reference material & education resources

- [x]  Links to software and tutorials on use

- [x]  Links to relevant beamlines

- [ ]  FAQs 

It is proposed that we have regular website management meetings every 2 months.

**Comment by tomarnoldess** [comment]
@jfkcooper you once said you could start a list of FAQs. Do you think you could create something to start us off on https://www.reflectometry.org/info/

**Comment by jfkcooper** [comment]
Added some FAQ, please all add more

**Comment by arm61** [comment]
We generally agree that this is done.
