### ISSUE TITLE
How do we give credit to the authors of content for our web page?

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#7]
If sombody puts a substantial amount of effort into creating and maintaing a web page then they may want to be credited for this effort.
For example, Adrian Rennie created most of the content on the list of neutron reflectometers & software (this content was copied from reflectometry.net)

**Comment by andyfaff** [comment]
If it's created via a GitHub commit then that'll be saved for posterity. Alternatively we could have a THANKS.txt in each repo where each new contributor could be mentioned, along with a 10 words or so on what they've done.

**Comment by tomarnoldess** [comment]
Thanks Andy, 
I think the concern was raised as one of visibility on the website. However it is true that all the repros should properly credit contributions and your suggestion is a good one.
For the website content perhaps we can put a short credit to the principle contributors at the bottom of each info page? But it is not clear to me what would qualify as a significant enough contribution to merit a credit and there's no way of policing it.

**Comment by tomarnoldess** [comment]
The plan is to write a standard text to put at the bottom of each webpage with contributed content. Anyone who edits the page can then add their name and contact details if they wish. We will compose some apppropriate text at the website editing session on 1st Oct.

**Comment by arm61** [comment]
Credit can now be given with the `author` tag in the yaml header of a post.
