### ISSUE TITLE
Add a bibliography and archive

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#8]
We would like a list of useful papers similar to http://www.reflectometry.net/reflect_bib.htm
We may also like to include an archive of published papers that is updated with new papers as they are published

**Comment by arm61** [comment]
Now being developed here https://github.com/reflectivity/reflectivity.github.io/blob/master/info/bibliography.md

Will leave up to Tom if we close.

**Comment by tomarnoldess** [comment]
Let's keep the issue open until we decide what to do about an archive of reflectometry papers

**Comment by tomarnoldess** [comment]
There's no progress on an archive. Closing this issue since the page exists and should be managed as part of the website
