### ISSUE TITLE
Add a link to the reflectometry twitterbot

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/edu_outreach#9]
Can we display tweets about reflectometry and maybe related techniques?

**Comment by arm61** [comment]
I have added the GISANS twitter bot to the homepage https://github.com/reflectivity/reflectivity.github.io/commit/9033810739a2de9eedaadaf0e039a57f26e3eab3

**Comment by tomarnoldess** [comment]
This is good enough for now, we can look at improving the prominence of the link or adding other relevant links in the future
